language: python
sudo: required
services:
  - docker

script:
  - docker build -t omero-prometheus-tools .
  - docker run omero-prometheus-tools omero-prometheus-counts.py --help
  - docker run omero-prometheus-tools omero-prometheus-sessions.py --help
